export const phoneticAlphabet = [
  { letter: "А", ref: "A", number: "1", src: "../audios/Alphabet/A.mp3" },
  { letter: "Б", ref: "B", number: "2", src: "../audios/Alphabet/B.mp3" },
  { letter: "В", ref: "V", number: "3", src: "../../audios/Alphabet/V.mp3" },
  { letter: "Г", ref: "G", number: "4", src: "../../audios/Alphabet/G.mp3" },
  { letter: "Д", ref: "D", number: "5", src: "../../audios/Alphabet/D.mp3" },
  { letter: "Е", ref: "E", number: "6", src: "../../audios/Alphabet/E.mp3" },
  { letter: "Ё", ref: "YO", number: "7", src: "../../audios/Alphabet/YO.mp3" },
  { letter: "Ж", ref: "J", number: "8", src: "../../audios/Alphabet/J.mp3" },
  { letter: "З", ref: "Z", number: "9", src: "../../audios/Alphabet/Z.mp3" },
  { letter: "И", ref: "I", number: "10", src: "../../audios/Alphabet/I.mp3" },
  { letter: "Й", ref: "Ii", number: "11", src: "../../audios/Alphabet/Ii.mp3" },
  { letter: "К", ref: "K", number: "12", src: "../../audios/Alphabet/K.mp3" },
  { letter: "Л", ref: "L", number: "13", src: "../../audios/Alphabet/L.mp3" },
  { letter: "М", ref: "M", number: "14", src: "../../audios/Alphabet/M.mp3" },
  { letter: "Н", ref: "N", number: "15", src: "../../audios/Alphabet/N.mp3" },
  { letter: "О", ref: "O", number: "16", src: "../../audios/Alphabet/O.mp3" },
  { letter: "П", ref: "P", number: "17", src: "../../audios/Alphabet/P.mp3" },
  { letter: "Р", ref: "R", number: "18", src: "../../audios/Alphabet/R.mp3" },
  { letter: "С", ref: "S", number: "19", src: "../../audios/Alphabet/S.mp3" },
  { letter: "Т", ref: "T", number: "20", src: "../../audios/Alphabet/T.mp3" },
  { letter: "У", ref: "Y", number: "21", src: "../../audios/Alphabet/Y.mp3" },
  { letter: "Ф", ref: "F", number: "22", src: "../../audios/Alphabet/F.mp3" },
  { letter: "Х", ref: "X", number: "23", src: "../../audios/Alphabet/X.mp3" },
  { letter: "Ц", ref: "TS", number: "24", src: "../../audios/Alphabet/TS.mp3" },
  {
    letter: "Ч",
    ref: "TCH",
    number: "25",
    src: "../../audios/Alphabet/TCH.mp3",
  },
  { letter: "Ш", ref: "SH", number: "26", src: "../../audios/Alphabet/SH.mp3" },
  {
    letter: "Щ",
    ref: "SCH",
    number: "27",
    src: "../../audios/Alphabet/SCH.mp3",
  },
  { letter: "Ъ", ref: "HC", number: "28", src: "../../audios/Alphabet/HC.mp3" },
  {
    letter: "Ы",
    ref: "YEE",
    number: "29",
    src: "../../audios/Alphabet/YEE.mp3",
  },
  { letter: "Ь", ref: "SC", number: "30", src: "../../audios/Alphabet/SC.mp3" },
  { letter: "Э", ref: "EA", number: "31", src: "../../audios/Alphabet/EA.mp3" },
  { letter: "Ю", ref: "U", number: "32", src: "../../audios/Alphabet/U.mp3" },
  { letter: "Я", ref: "YA", number: "33", src: "../../audios/Alphabet/YA.mp3" },
];
